development:
  adapter: mysql2
  encoding: utf8
  database: flower_development
  pool: 30
  username: root
  password: mystery
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: flower_test
  pool: 30
  username: pkwde_test
  password: bc9TXNbMQI
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: flower_production
  username: some
  password: password
  encoding: UTF8
  reconnect: true
  socket: /tmp/mysql.sock
